package com.hankkin.itround.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hankkin.itround.bean.GankBean;

import com.hankkin.itround.greendao.dao.GankBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankBeanDaoConfig;

    private final GankBeanDao gankBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankBeanDaoConfig = daoConfigMap.get(GankBeanDao.class).clone();
        gankBeanDaoConfig.initIdentityScope(type);

        gankBeanDao = new GankBeanDao(gankBeanDaoConfig, this);

        registerDao(GankBean.class, gankBeanDao);
    }
    
    public void clear() {
        gankBeanDaoConfig.clearIdentityScope();
    }

    public GankBeanDao getGankBeanDao() {
        return gankBeanDao;
    }

}
