package com.hankkin.itround.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hankkin.itround.db.StringConverter;
import java.util.List;

import com.hankkin.itround.bean.GankBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "gankbean".
*/
public class GankBeanDao extends AbstractDao<GankBean, Void> {

    public static final String TABLENAME = "gankbean";

    /**
     * Properties of entity GankBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, String.class, "_id", false, "_id");
        public final static Property CreatedAt = new Property(1, String.class, "createdAt", false, "createdAt");
        public final static Property Desc = new Property(2, String.class, "desc", false, "desc");
        public final static Property PublishedAt = new Property(3, String.class, "publishedAt", false, "publishedAt");
        public final static Property Source = new Property(4, String.class, "source", false, "source");
        public final static Property Type = new Property(5, String.class, "type", false, "type");
        public final static Property Url = new Property(6, String.class, "url", false, "url");
        public final static Property Used = new Property(7, boolean.class, "used", false, "used");
        public final static Property Who = new Property(8, String.class, "who", false, "who");
        public final static Property Images = new Property(9, String.class, "images", false, "IMAGES");
    }

    private final StringConverter imagesConverter = new StringConverter();

    public GankBeanDao(DaoConfig config) {
        super(config);
    }
    
    public GankBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"gankbean\" (" + //
                "\"_id\" TEXT," + // 0: _id
                "\"createdAt\" TEXT," + // 1: createdAt
                "\"desc\" TEXT," + // 2: desc
                "\"publishedAt\" TEXT," + // 3: publishedAt
                "\"source\" TEXT," + // 4: source
                "\"type\" TEXT," + // 5: type
                "\"url\" TEXT," + // 6: url
                "\"used\" INTEGER NOT NULL ," + // 7: used
                "\"who\" TEXT," + // 8: who
                "\"IMAGES\" TEXT);"); // 9: images
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"gankbean\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GankBean entity) {
        stmt.clearBindings();
 
        String _id = entity.get_id();
        if (_id != null) {
            stmt.bindString(1, _id);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(2, createdAt);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(3, desc);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindString(4, publishedAt);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(5, source);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
        stmt.bindLong(8, entity.getUsed() ? 1L: 0L);
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(9, who);
        }
 
        List images = entity.getImages();
        if (images != null) {
            stmt.bindString(10, imagesConverter.convertToDatabaseValue(images));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GankBean entity) {
        stmt.clearBindings();
 
        String _id = entity.get_id();
        if (_id != null) {
            stmt.bindString(1, _id);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(2, createdAt);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(3, desc);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindString(4, publishedAt);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(5, source);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(6, type);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
        stmt.bindLong(8, entity.getUsed() ? 1L: 0L);
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(9, who);
        }
 
        List images = entity.getImages();
        if (images != null) {
            stmt.bindString(10, imagesConverter.convertToDatabaseValue(images));
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public GankBean readEntity(Cursor cursor, int offset) {
        GankBean entity = new GankBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // createdAt
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // desc
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // publishedAt
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // source
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // url
            cursor.getShort(offset + 7) != 0, // used
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // who
            cursor.isNull(offset + 9) ? null : imagesConverter.convertToEntityProperty(cursor.getString(offset + 9)) // images
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GankBean entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCreatedAt(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDesc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPublishedAt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSource(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUsed(cursor.getShort(offset + 7) != 0);
        entity.setWho(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setImages(cursor.isNull(offset + 9) ? null : imagesConverter.convertToEntityProperty(cursor.getString(offset + 9)));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(GankBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(GankBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(GankBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
